"""Prepare pinned CC0 Gretsch recordings. Requires NumPy/SciPy, never at runtime."""
import hashlib
import json
from pathlib import Path
import sys
import warnings
import numpy as np
from scipy.io import wavfile
from scipy.signal import correlate, resample_poly

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / 'assets/samples/clean-guitar'
ROOT = Path(sys.argv[1])
warnings.filterwarnings('ignore', category=wavfile.WavFileWarning)
sources = json.loads(Path(__file__).with_name('sources.json').read_text())
manifest = []

for s in sources:
    raw = (ROOT / s['path']).read_bytes()
    assert hashlib.sha1(b'blob '+str(len(raw)).encode()+b'\0'+raw).hexdigest() == s['sha']
    rate, pcm = wavfile.read(ROOT / s['path'])
    x = pcm.astype(np.float64) / 2**(8*pcm.dtype.itemsize-1)
    if x.ndim == 2:
        x = x.mean(axis=1)
    if rate != 44100:
        x = resample_poly(x, 44100, rate)
    rate = 44100
    x -= x.mean()
    # Align to the pick transient, preserving 1 ms of pre-attack, never skip it.
    onset = max(0, int(np.flatnonzero(abs(x) > max(abs(x))*.02)[0])-44)
    x = x[onset:rate*8+onset]
    expected = 440*2**((s['midi']-69)/12)
    estimates = []
    for start in np.linspace(.10, .40, 7):
        y = x[int(start*rate):int((start+.20)*rate)].copy()
        y -= y.mean()
        c = correlate(y,y,mode='full',method='fft')[len(y)-1:]
        c /= np.arange(len(y),0,-1)
        lo, hi = max(2,int(rate/(expected*1.08))), int(rate/(expected*.92))
        k = lo + int(np.argmax(c[lo:hi+1]))
        assert lo < k < hi, (s['path'], k, lo, hi)
        d = .5*(c[k-1]-c[k+1])/(c[k-1]-2*c[k]+c[k+1])
        estimates.append(rate/(k+d))
    ref = float(np.median(estimates))
    # Peak-match takes so articulation controls timbre; score volume controls gain.
    gain = .8/max(abs(x))
    x *= gain
    x[:22] *= np.linspace(0,1,22)  # half-ms edge smoothing preserves the pluck
    n = min(2205,len(x)); x[-n:] *= np.linspace(1,0,n)
    key = f"guitar-{s['midi']}-{s['dynamic']}-{s['take']}"
    levels = []
    for level in range(7):
        y = resample_poly(x,1,2**level) if level else x
        data = np.rint(np.clip(y,-1,1)*32767).astype('<i2').tobytes()
        name = f'{key}-{level}.pcm'; (OUT/name).write_bytes(data)
        levels.append({'file':name,'frames':len(y),'sha256':hashlib.sha256(data).hexdigest()})
    manifest.append({**s,'reference_hz':ref,'pitch_spread_cents':float(np.std(1200*np.log2(np.array(estimates)/expected))),'trimmed_frames':onset,'gain':gain,'levels':levels})
    print(key, round(ref,3), 'Hz')
(OUT/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
lines = ['// Generated by tools/clean-guitar/prepare.py; do not hand-edit.', 'use super::{GuitarPitch, Sample};', 'pub(super) static GUITAR: &[GuitarPitch] = &[']
for midi in sorted({s['midi'] for s in manifest}):
    lines.append(f'GuitarPitch {{ nominal_hz: {440*2**((midi-69)/12):.10f},')
    for dynamic in ['medium','firm']:
        lines.append(f'{dynamic}: [')
        for s in manifest:
            if s['midi'] != midi or s['dynamic'] != dynamic: continue
            levels = ', '.join('include_bytes!("../../assets/samples/clean-guitar/'+l['file']+'")' for l in s['levels'])
            lines.append(f'Sample {{ reference_hz: {s["reference_hz"]:.10f}, levels: &[{levels}], sustain: None }},')
        lines.append('],')
    lines.append('},')
lines.append('];')
(REPO/'src/voice_rendering/clean_guitar_samples.rs').write_text('\n'.join(lines)+'\n')
