"""Prepare the pinned VSCO subset. Requires numpy/scipy, only at asset-build time.

Outputs mono PCM16 plus anti-alias mip levels and measured reference frequencies.
The Ahess executable embeds these assets; playback never reads files or decodes WAV.
"""
import hashlib
import json
from pathlib import Path
import re
import sys
import warnings
import numpy as np
from scipy.io import wavfile
from scipy.signal import correlate, resample_poly

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / 'assets/samples/vsco2'
ROOT = Path(sys.argv[1])
warnings.filterwarnings('ignore', category=wavfile.WavFileWarning)
sources = json.loads(Path(__file__).with_name('sources.json').read_text())
notes = {'C':0,'D':2,'E':4,'F':5,'G':7,'A':9,'B':11}
manifest = []


def measure(x, rate, expected, harp):
    estimates = []
    # Harp high notes decay quickly; measure early rather than room noise.
    starts = np.linspace(.025, .18, 7) if harp else np.linspace(.5, 2.8, 12)
    for start in starts:
        y = x[int(start*rate):int((start + (.16 if harp else .2))*rate)].copy()
        y -= np.mean(y)
        if len(y)<128: continue
        # Unbiased autocorrelation avoids systematic high-pitch bias on decays.
        c = correlate(y,y,mode='full',method='fft')[len(y)-1:]
        c /= np.arange(len(y),0,-1)
        lo, hi = int(rate/(expected*1.10)), int(rate/(expected*.90))
        lo, hi = max(2,lo), min(len(c)-2,hi)
        k = lo + int(np.argmax(c[lo:hi+1]))
        assert lo<k<hi, (expected, k, lo, hi)
        d = .5*(c[k-1]-c[k+1])/(c[k-1]-2*c[k]+c[k+1])
        estimates.append(rate/(k+d))
    return float(np.median(estimates)), float(np.std(1200*np.log2(np.array(estimates)/expected)))

for s in sources:
    inst=s['instrument']; name=Path(s['path']).name
    note,sharp,octave=re.search(r'_([A-G])(#?)(\d)_',name).groups()
    midi=12*(int(octave)+1)+notes[note]+bool(sharp)+(0 if inst=='harp' else 12)
    # Keep a useful, well-recorded harp range; high notes have very short tones.
    if inst=='harp' and (midi>83 or name.startswith('KSHarp_G1')): continue
    p=ROOT/s['path']; raw=p.read_bytes()
    assert hashlib.sha1(b'blob '+str(len(raw)).encode()+b'\0'+raw).hexdigest()==s['sha']
    rate,x=wavfile.read(p); assert rate==44100
    x=x.astype(np.float64)/(2**(8*x.dtype.itemsize-1))
    if x.ndim==2:x=x.mean(axis=1)
    x-=np.mean(x)
    # Remove leading silence only; retain 10 ms ahead of the first audible block.
    block=220; rms=np.sqrt(np.mean(x[:len(x)//block*block].reshape(-1,block)**2,axis=1))
    onset=max(0,int(np.flatnonzero(rms>max(rms)*.02)[0])*block-441)
    x=x[onset:]
    ref,spread=measure(x,rate,440*2**((midi-69)/12),inst=='harp')
    if inst!='harp':
        assert len(x)>int(3.8*rate)
        x=x[:int(3.8*rate)]
        loop=(int(1.25*rate),int(3.5*rate),int(.08*rate))
        level=np.sqrt(np.mean(x[int(.5*rate):int(3*rate)]**2))
        gain=min(.13/max(level,1e-9),.85/max(abs(x)))
    else:
        # Keep the natural decay, up to 10 seconds, and fade its last 30 ms.
        x=x[:rate*10];loop=None;gain=.8/max(abs(x))
    x*=gain
    n=min(220,len(x)); x[:n]*=np.linspace(0,1,n)
    n=min(1323,len(x)); x[-n:]*=np.linspace(1,0,n)
    key=f'{inst}-{midi}'
    levels=[]
    for level in range(7):
        y=resample_poly(x,1,2**level) if level else x
        pcm=np.rint(np.clip(y,-1,1)*32767).astype('<i2').tobytes()
        file=f'{key}-{level}.pcm';(OUT/file).write_bytes(pcm)
        levels.append({'file':file,'frames':len(y),'sha256':hashlib.sha256(pcm).hexdigest()})
    manifest.append({'instrument':inst,'source':s['path'],'source_git_blob':s['sha'],'nominal_midi':midi,'reference_hz':ref,'pitch_spread_cents':spread,'trimmed_frames':onset,'gain':gain,'loop':loop,'levels':levels})
    print(key,round(ref,3),'cents',round(1200*np.log2(ref/(440*2**((midi-69)/12))),1),'spread',round(spread,1))
manifest.sort(key=lambda s:(s['instrument'],s['reference_hz']))
(OUT/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
lines=['// Generated by tools/vsco/prepare.py; do not hand-edit.','use super::{Sample, SampleLoop};']
for inst in ['cello','flute','clarinet','harp']:
    lines.append(f'pub(super) static {inst.upper()}: &[Sample] = &[')
    for s in manifest:
        if s['instrument']!=inst:continue
        levels=', '.join('include_bytes!("../../assets/samples/vsco2/'+l['file']+'")' for l in s['levels'])
        lp='None' if s['loop'] is None else 'Some(SampleLoop { start: %s.0, end: %s.0, crossfade: %s.0 })'%tuple(s['loop'])
        lines.append(f'    Sample {{ reference_hz: {s["reference_hz"]:.10f}, levels: &[{levels}], sustain: {lp} }},')
    lines.append('];')
(REPO/'src/voice_rendering/vsco_samples.rs').write_text('\n'.join(lines)+'\n')
print('Prepared',len(manifest),'samples')
